### ISSUE TITLE
TFT Display from Amazon does not match the one in project

### ISSUE THREAD

**Issue by peterbuxton** [rbwhipple/VRA-FS#3]
Mr. Whipple:

I bought your book, _Vintage Radio Alignment From Scratch_, and it is a wonderful reference. I also enthusiastically began to build your alignment instrument and bought all the parts on the list. You specify the **DSD TECH 1.8 Inch TFT LCD from Amazon**. On Amazon I found one with [exactly that title](https://www.amazon.com/DSD-TECH-Display-Interface-Arduino/dp/B07WDJ3TV6) but it turned out to be 11 pins with completely different labels than the 10-pin display in the schematic. In fact, I can't even find a 10-pin LCD that matches the title or schematic pinout. 

The display I ordered from Amazon uses SPI communication but your Arduino code doesn't indicate that (or even which protocol is used). Is there a way to make the SPI display from Amazon work in your Arduino code or is there a different display available that matches your code? Thank you.

Peter Buxton

**Comment by b-forsberg** [comment]
Peter, my name is Bruce and I have successfully built Mr. Whipple's device.
I used the Adafruit 358 display. I got mine at Mouser at:
https://www.mouser.com/ProductDetail/485-358

The Adafruit 358 is available elsewhere as well.
Good Luck building your device.

Bruce Forsberg

**Comment by peterbuxton** [comment]
Hello Bruce,

Thank you so much for this information!

I may have to buy the Adafruit 358, but first I hope to see if I can modify the Arduino code to make my DSD display work. It uses the T7735 driver chip. 

The Adafruit documentation says that the display uses SPI and is written that 

"two libraries need to be downloaded and installed: first is the ST7735 library (this contains the low-level code specific to this device), and second is the Adafruit GFX Library." 

Did you have to add those libraries to your code or did the Adafruit display work with the unmodified code from this project?

Peter

**Comment by peterbuxton** [comment]
I just wanted to leave a note saying that with Bruce Forsberg's information, I was able to find information on the Internet to translate the Adafruit 358 display's pin functions to my DSD display's pins to make it work in a test circuit, so now I should be able to use it with Mr. Whipple's code.
